#!/bin/bash

# Deploy TrueFans Connect with SSL support (default configuration)
echo "🚀 Deploying TrueFans Connect with SSL support..."

# Set default domain if not provided
DOMAIN=${1:-"truefansconnect.com"}

echo "📋 Configuration:"
echo "   Domain: $DOMAIN"
echo "   Email: aldenlemberg@gmail.com"
echo ""

# Create acme.json if it doesn't exist
if [ ! -f acme.json ]; then
    echo "📄 Creating acme.json for SSL certificates..."
    touch acme.json
    chmod 600 acme.json
fi

# Update domain in docker-compose.yml if different from default
if [ "$DOMAIN" != "truefansconnect.com" ]; then
    echo "🔧 Updating domain to: $DOMAIN"
    sed -i.bak "s/truefansconnect.com/$DOMAIN/g" docker-compose.yml
fi

# Build and deploy
echo "🏗️  Building and deploying..."
export DOMAIN=$DOMAIN
docker-compose down
docker-compose build --no-cache
docker-compose up -d

echo ""
echo "✅ Deployment completed!"
echo ""
echo "🌐 Your application should be available at:"
echo "   https://$DOMAIN"
echo ""
echo "📊 Traefik Dashboard:"
echo "   http://localhost:8080"
echo ""
echo "📝 Important notes:"
echo "   - SSL certificate will be automatically generated by Let's Encrypt"
echo "   - First visit might take a few minutes for certificate generation"
echo "   - Make sure your domain points to this server's IP address"
echo ""
echo "🔍 To check deployment status:"
echo "   docker-compose logs -f"
echo ""
echo "🛑 To stop the deployment:"
echo "   docker-compose down" 