#!/bin/bash

# Deploy TrueFans Connect with SSL support using Traefik
echo "🚀 Deploying TrueFans Connect with SSL support..."

# Check if domain is provided
if [ -z "$1" ]; then
    echo "❌ Error: Please provide your domain name"
    echo "Usage: ./deploy-with-ssl.sh yourdomain.com"
    echo "Example: ./deploy-with-ssl.sh truefansconnect.com"
    exit 1
fi

DOMAIN=$1
EMAIL=${2:-"aldenlemberg@gmail.com"}

echo "📋 Configuration:"
echo "   Domain: $DOMAIN"
echo "   Email: $EMAIL"
echo ""

# Update configuration files with the provided domain
echo "🔧 Updating configuration files..."

# Update traefik.yml with the provided email (if different from default)
if [ "$EMAIL" != "aldenlemberg@gmail.com" ]; then
    sed -i.bak "s/aldenlemberg@gmail.com/$EMAIL/g" traefik.yml
fi

# Update docker-compose.traefik.yml with the provided domain
sed -i.bak "s/truefansconnect.com/$DOMAIN/g" docker-compose.traefik.yml

# Create acme.json if it doesn't exist
if [ ! -f acme.json ]; then
    echo "📄 Creating acme.json for SSL certificates..."
    touch acme.json
    chmod 600 acme.json
fi

# Build and deploy
echo "🏗️  Building and deploying..."
docker-compose -f docker-compose.traefik.yml down
docker-compose -f docker-compose.traefik.yml build --no-cache
docker-compose -f docker-compose.traefik.yml up -d

echo ""
echo "✅ Deployment completed!"
echo ""
echo "🌐 Your application should be available at:"
echo "   https://$DOMAIN"
echo ""
echo "📊 Traefik Dashboard:"
echo "   http://localhost:8080"
echo ""
echo "📝 Important notes:"
echo "   - SSL certificate will be automatically generated by Let's Encrypt"
echo "   - First visit might take a few minutes for certificate generation"
echo "   - Make sure your domain points to this server's IP address"
echo ""
echo "🔍 To check deployment status:"
echo "   docker-compose -f docker-compose.traefik.yml logs -f"
echo ""
echo "🛑 To stop the deployment:"
echo "   docker-compose -f docker-compose.traefik.yml down" 