version: '3.8'

services:
  app:
    build: .
    container_name: truefans-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3009
      - HOSTNAME=0.0.0.0
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: truefans-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro  # Mount your SSL certificates here
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 