version: '3.8'

services:
  app:
    build: .
    container_name: truefans-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3009
      - HOSTNAME=0.0.0.0
    networks:
      - traefik-network
    labels:
      # Enable Traefik
      - "traefik.enable=true"
      
      # HTTP Router (redirects to HTTPS)
      - "traefik.http.routers.truefans-http.entryPoints=web"
      - "traefik.http.routers.truefans-http.rule=Host(`truefansconnect.com`)"
      - "traefik.http.routers.truefans-http.middlewares=redirect-to-https"
      
      # HTTPS Router (main application)
      - "traefik.http.routers.truefans-https.entryPoints=websecure"
      - "traefik.http.routers.truefans-https.rule=Host(`truefansconnect.com`)"
      - "traefik.http.routers.truefans-https.tls=true"
      - "traefik.http.routers.truefans-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.truefans-https.middlewares=gzip"
      
      # Service definition
      - "traefik.http.services.truefans.loadbalancer.server.port=3009"
      
      # Middlewares
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./acme.json:/acme.json
    networks:
      - traefik-network
    command:
      - "--configFile=/etc/traefik/traefik.yml"

networks:
  traefik-network:
    driver: bridge 